### PR TITLE
Change disconnect function to avoid CLOSE_WAIT [rspadim]

### PR DESCRIPTION
**Pull request by ashnazg**
This reapplies @rspadim 's patch from PR #4 to the master branch.

### CODE REVIEW

**Comment by ashnazg** [comment]
@alecpl , do you think, as per your 2016 comment on original PR #4, that this change might no longer be needed?

**Comment by ashnazg** [comment]
@alecpl , I'm also wondering if all these additional `socket_*` calls at the end might solve http://pear.php.net/bugs/bug.php?id=18176...

**Comment by alecpl** [comment]
I'd like to hear from anyone that it's still an issue on recent PHP versions.

**Comment by ashnazg** [comment]
No feedback since 2017, so closing.

**Pull request closed without merging**
